### ISSUE TITLE
Testing with the Firestore emulator

### ISSUE THREAD

**Issue by nickbauman** [polvotech/firestore-clj#1]
This is a wonderful contribution. I want to use it in the Firestore version of my [Datastore library for AppEngine](https://github.com/nickbauman/gaeclj-ds). In that library I'm using the AppEngine test doubles for Datastore but there is no such thing for Firestore. Only the emulator. How do you write good tests with this thing?

**Comment by lurodrigo** [comment]
I'm not sure how to do use Firestore emulator. This lib is based on the Java Admin SDK and AFAIK only Android, iOS, Web, and Node.js Admin SDK support emulators (see [here](https://firebase.google.com/docs/emulator-suite/connect_and_prototype?database=Firestore)). Manye functions here take a `com.google.cloud.firestore.Firestore` instance as an argument, maybe there's an undocumented way get an instance connecting with the emulator. How be glad to add a function for it if there's one.

The hack I'm doing by now is using a dev project with a Firestore instance and performing populate-test-delete against it. We have `purge!` to delete collections and documents recursively. Not great, but that's what we have for now.

**Comment by nickbauman** [comment]
Ah, you're right, sadly. Ideally we would be able to find the Firestore test doubles in the package `com.google.appengine.tools.development.testing` where you already find a `LocalDatastoreServiceTestConfig` which works flawlessly when testing local datastore writes and reads for tests. Ideally there would be a `LocalFirestoreServiceTestConfig` in there too...

I think I'm going to do it like you: just create a dev project, use a service account for that and write my tests against that. Thank you very much. Great contribution.

**Comment by lurodrigo** [comment]
Hi @nickbauman! @codestiff made a great contribution and managed to make the emulator work with firestore-clj, you can already try it in 1.2.1. Since it's experimental, any feedback would be appreciated. Thanks!

**Comment by nickbauman** [comment]
Wow this is great. I scanned the contribution. Will report back.

**Comment by nickbauman** [comment]
I got a basic error:

```
user=> (require '[firestore-clj.core :as f])
Syntax error (ClassNotFoundException) compiling . at (firestore_clj/google.clj:32:15).
io.grpc.ManagedChannel
```

**Comment by codestiff** [comment]
Does `[io.grpc/grpc-core "1.24.1" :scope "provided"]` need to be added to `profiles.clj` ?

**Comment by lurodrigo** [comment]
I just made a new test project and this error hasn't shown up, require worked fine. It probably has to do with `grpc-core`, the dependency tree is [messy](https://github.com/technomancy/leiningen/issues/2251) and has version ranges, so if you're using other google libs this is probably the cause. But anyway I'd like to have a solution or at least a hack for that so users don't suffer.

**Comment by lurodrigo** [comment]
Does `[polvo/firestore-clj "1.2.1" :exclusions [io.grpc/grpc-core]]` help?

**Comment by codestiff** [comment]
Yeah, I'm not sure what the "correct" way to handle the grpc dependency tree

**Comment by nickbauman** [comment]
Yeah I monkeyed around with exclusions earlier to no avail. I’ll try again tomorrow after work.

**Comment by lurodrigo** [comment]
I'm really sorry for the inconvenience. That's a very weird problem, does that happen even in a project where firestore-clj is the only dependency? I even deleted my local `.m2` folder and downloaded the dependencies again, but wasn't able to reproduce your error. It's even weirder because we have not added dependencies (only in the `:dev` profile).
