### ISSUE TITLE
Issue with add! and merge!

### ISSUE THREAD

**Issue by amarjeet000** [polvotech/firestore-clj#3]
Hi,

Suddenly I started getting the following error in the case of create (add!) and update (merge!) calls:

`Execution error (NoSuchMethodError) at com.google.firestore.v1.Document/writeTo (Document.java:480).
com.google.protobuf.GeneratedMessageV3.serializeStringMapTo(Lcom/google/protobuf/CodedOutputStream;Lcom/google/protobuf/MapField;Lcom/google/protobuf/MapEntry;I)V`

A quick search indicates that there are potentially version issues wrt gRPC/Protobuff. But it is surprising because, the same operations were fine a day ago.

I am wondering if you also have come across the same issue? I tried some deps exclusions, but it hasn't worked yet.

**Comment by lurodrigo** [comment]
Unfortunately I can't reproduce this issue, both `add!` and `merge!` are working fine here. Could you provide more details?

Anyway, this lib don't have a direct dependency on gRPC, only on `[com.google.firebase/firebase-admin "6.12.2"]`. gRPC dependency trees are [notably messy](https://github.com/technomancy/leiningen/issues/2251), leading to some non-repeatability issues. Did you add a dependency (directly or indirectly) on gRPC recently? Maybe that's leading to these issues.

**Comment by amarjeet000** [comment]
It appears that my project is somehow corrupted. I just tried these operations in a fresh new project and things are working fine. My bad it is :( I will close this issue.
