### ISSUE TITLE
Clarify intention of emulator client

### ISSUE THREAD

**Issue by codestiff** [polvotech/firestore-clj#5]
I'll formalize the emulator code in this issue: https://github.com/codestiff/firestore-clj/issues/1

Until then let me give you a quick run down. 
The code here: https://github.com/polvotech/firestore-clj/pull/4
was designed to avoid needing the java process running your clojure to have the env variable, `FIRESTORE_EMULATOR_HOST`

Background:
Most of what I did is analyze the google cloud firestore client. Located here:  https://github.com/googleapis/java-firestore

We can see where I found the idea for `FakeCredentials` here: https://github.com/googleapis/java-firestore/blob/813e246f8ec5d25e8101480e3e21270160fdf2cc/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java#L264

Observations:
* It looks like the source does not want you to connect to the emulator outside of setting the 
env variable.
  * See: https://github.com/googleapis/java-firestore/blob/813e246f8ec5d25e8101480e3e21270160fdf2cc/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java#L230 
  * And here: https://github.com/googleapis/java-firestore/blob/813e246f8ec5d25e8101480e3e21270160fdf2cc/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreOptions.java#L59
* I specifically want to be able to connect to the emulator without setting the environment variable. It's possible (but not verified by me) that some of the configuration steps can be removed if that use case is replaced w/ requiring users to set the environment variable, `FIRESTORE_EMULATOR_HOST`

**Comment by codestiff** [comment]
Let me know if you have any questions/concerns @lurodrigo

**Comment by lurodrigo** [comment]
To be fair, I was only able to run the emulator after setting the env var.  If it wasn't set, the emulator client connected, but every operation, even printing, threw ```io.grpc.StatusRuntimeException: UNAUTHENTICATED: Credentials require channel with PRIVACY_AND_INTEGRITY security level. Observed security level: NONE```

**Comment by lurodrigo** [comment]
But the links are great anyway! I think I'll dig into the sources deeper later. I agree that not having to set an env var is more convenient, if we make it so emulator-client works reliably that way, that'd be great! I'll try to investigate why this doesn't work for me.

**Comment by codestiff** [comment]
I'm going to close this until there are more questions
